name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2.8.0
        with:
          ghc-version: "9.10.1"
          cabal-version: "3.12.1.0"
      - name: cache ~/.cabal
        uses: actions/cache@v4
        with:
          path: ~/.cabal
          key: ${{ runner.os }}-cabal-${{ hashFiles('markdownrealcode.cabal') }}
          restore-keys: ${{ runner.os }}-cabal-
      - run: cabal update
      - run: cabal build -j2
      - run: cabal test -j2
